# Generated by Django 2.2.12 on 2020-04-14 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Com',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='1', max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('Cinfo', models.CharField(max_length=20)),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='logo')),
                ('Companyprofile', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '企业数据',
                'verbose_name_plural': '企业表',
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='user', verbose_name='user')),
                ('resume', models.FileField(upload_to='cv', verbose_name='resume')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '简历数据',
                'verbose_name_plural': '简历表',
            },
        ),
        migrations.CreateModel(
            name='Zp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('jobType', models.CharField(max_length=40)),
                ('jobName', models.CharField(max_length=40)),
                ('jobTitle', models.CharField(max_length=20)),
                ('pre', models.CharField(max_length=20)),
                ('academic', models.CharField(max_length=20)),
                ('welfare', models.TextField()),
                ('jobprofile', models.TextField()),
                ('need_number', models.IntegerField()),
                ('com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZpModel.Com')),
            ],
            options={
                'verbose_name': '招聘数据',
                'verbose_name_plural': '招聘表',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('tim', models.CharField(max_length=20)),
                ('need', models.CharField(max_length=20)),
                ('is_have', models.BooleanField(default=False)),
                ('result', models.BooleanField()),
                ('com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZpModel.Com')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZpModel.CV')),
                ('zp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ZpModel.Zp')),
            ],
        ),
    ]
