# Generated by Django 2.2.12 on 2020-04-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZpModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='result',
            field=models.BooleanField(null=True),
        ),
    ]
