# Generated by Django 2.2.12 on 2020-05-12 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20, verbose_name='城市')),
                ('name', models.CharField(max_length=20, verbose_name='公交车线路名称')),
                ('start', models.IntegerField(verbose_name='开始运行时间')),
                ('end', models.IntegerField(verbose_name='结束运行时间')),
                ('count', models.IntegerField(verbose_name='每趟间隔时间')),
                ('need', models.IntegerField(verbose_name='站点间隔时间')),
                ('money', models.IntegerField(verbose_name='票价')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='公交车站点名称')),
                ('number', models.IntegerField(verbose_name='第几站')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.Line')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_ID', models.CharField(max_length=50, verbose_name='电子身份证')),
                ('car_type', models.CharField(max_length=20, verbose_name='车辆型号')),
                ('car_name', models.CharField(max_length=20, verbose_name='驾驶员名字')),
                ('car_com', models.CharField(max_length=20, verbose_name='运行公司')),
                ('car_phone', models.CharField(max_length=20, verbose_name='司机电话')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.Line')),
            ],
        ),
    ]
